In [1]:
import pandas as pd

In [2]:
senseData = pd.read_csv("Lerror1.csv", header = None)
senseData.columns = ["Case_ID", "Timestamp", "Type", "Sensor"]
senseData

         Case_ID                      Timestamp            Type    Sensor
0     2022-09-02  2022-09-02T08:11:01.023211343  PresenceSensor    door_A
1     2022-09-02  2022-09-02T08:11:05.058745248     FloorSensor   sens4_A
2     2022-09-02  2022-09-02T08:11:07.680065591     FloorSensor   sens1_A
3     2022-09-02  2022-09-02T08:14:07.922706277     FloorSensor   sens1_A
4     2022-09-02  2022-09-02T08:14:11.751133401     FloorSensor   sens3_A
...          ...                            ...             ...       ...
3602  2022-12-10  2022-12-10T08:28:31.391227633     FloorSensor   sens3_C
3603  2022-12-10  2022-12-10T08:28:57.633868319     FloorSensor   sens4_C
3604  2022-12-10  2022-12-10T08:29:00.048081881     FloorSensor  sense1_C
3605  2022-12-10  2022-12-10T08:29:30.048081881     FloorSensor  sense1_C
3606  2022-12-10  2022-12-10T08:30:00.048081881     FloorSensor  sense1_C

[3607 rows x 4 columns]

In [3]:
newdataset = pd.DataFrame(columns =["Case_ID", "Timestamp", "Type", "Sensor", "Label", "Activity_ID"])
temp = 0
i = 0

for index, row in senseData.iterrows():
    activity = row["Sensor"][-1]
    new_row = {}
    new_row["Case_ID"] = row["Case_ID"]
    new_row["Timestamp"] = row["Timestamp"]
    new_row["Type"] = row["Type"]
    new_row["Sensor"] = row["Sensor"]
    # First row of the dataset
    if(temp == 0 and i == 0):
        new_row["Label"] = activity
        new_row["Activity_ID"] = i
        temp = activity
    # if the actual row has the same label of the stored, then is the same group
    elif(activity == temp):
        new_row["Activity_ID"] = i
        new_row["Label"] = activity
    # if the label mismatch, start a new group
    elif(activity != temp):
        i = i+1
        temp = activity
        new_row["Activity_ID"] = i
        new_row["Label"] = activity
    newdataset = newdataset.append(new_row, ignore_index=True)
newdataset

,Case_ID,Timestamp,Type,Sensor,Label,Activity_ID
0,2022-09-02,2022-09-02T08:11:01.023211343,PresenceSensor,door_A,A,0
1,2022-09-02,2022-09-02T08:11:05.058745248,FloorSensor,sens4_A,A,0
2,2022-09-02,2022-09-02T08:11:07.680065591,FloorSensor,sens1_A,A,0
3,2022-09-02,2022-09-02T08:14:07.922706277,FloorSensor,sens1_A,A,0
4,2022-09-02,2022-09-02T08:14:11.751133401,FloorSensor,sens3_A,A,0
...,...,...,...,...,...,...
3602,2022-12-10,2022-12-10T08:28:31.391227633,FloorSensor,sens3_C,C,228
3603,2022-12-10,2022-12-10T08:28:57.633868319,FloorSensor,sens4_C,C,228
3604,2022-12-10,2022-12-10T08:29:00.048081881,FloorSensor,sense1_C,C,228
3605,2022-12-10,2022-12-10T08:29:30.048081881,FloorSensor,sense1_C,C,228
3606,2022-12-10,2022-12-10T08:30:00.048081881,FloorSensor,sense1_C,C,228

In [4]:
# Save the file
newdataset.to_csv("Lerror1_labeled.csv", index=False)